export const productList = [
   {
      name: "간장 돼지 불고기(1인)",
      brand: "밀샵",
      img: "https://mealkit-s3.s3.ap-northeast-2.amazonaws.com/1.jpg",
      price: 8900,
      sale: 10,
      status: 1,
      stock: 100,
      detail: "부드러운 돼지고기를 간장 양념으로 조리한 메뉴입니다.",
      create_date: "2024-11-06",
   },
   {
      name: "[The : 푸짐한] 햄폭탄 부대전골",
      brand: "밀샵",
      img: "https://mealkit-s3.s3.ap-northeast-2.amazonaws.com/2.jpg",
      price: 15200,
      sale: 20,
      status: 1,
      stock: 50,
      detail: "다양한 재료가 가득한 부대전골입니다.",
      create_date: "2024-11-06",
   },
   {
      name: "[The : 푸짐한] 서울식 불고기 전골",
      brand: "밀샵",
      img: "https://mealkit-s3.s3.ap-northeast-2.amazonaws.com/3.jpg",
      price: 11900,
      sale: 5,
      status: 1,
      stock: 60,
      detail: "서울식 스타일의 불고기 전골입니다.",
      create_date: "2024-11-06",
   },
   {
      name: "간장 벌집 껍데기",
      brand: "밀샵",
      img: "https://mealkit-s3.s3.ap-northeast-2.amazonaws.com/4.jpg",
      price: 6500,
      sale: 0,
      status: 1,
      stock: 80,
      detail: "간장 양념이 잘 배인 껍데기입니다.",
      create_date: "2024-11-06",
   },
   {
      name: "팥 붕어빵(1kg)",
      brand: "밀샵",
      img: "https://mealkit-s3.s3.ap-northeast-2.amazonaws.com/5.jpg",
      price: 15500,
      sale: 0,
      status: 1,
      stock: 40,
      detail: "달콤한 팥이 들어간 붕어빵입니다.",
      create_date: "2024-11-06",
   },
   {
      name: "슈크림 붕어빵(1kg)",
      brand: "밀샵",
      img: "https://mealkit-s3.s3.ap-northeast-2.amazonaws.com/6.jpg",
      price: 15500,
      sale: 15,
      status: 1,
      stock: 30,
      detail: "부드러운 슈크림이 가득한 붕어빵입니다.",
      create_date: "2024-11-06",
   },
   {
      name: "[킹콩] 킹콩 칠리비프 부대찌개",
      brand: "밀샵",
      img: "https://mealkit-s3.s3.ap-northeast-2.amazonaws.com/7.jpg",
      price: 16900,
      sale: 10,
      status: 1,
      stock: 50,
      detail: "킹콩 스타일의 칠리비프 부대찌개입니다.",
      create_date: "2024-11-06",
   },
   {
      name: "[두찜] 두찜 납작면 닭갈비",
      brand: "밀샵",
      img: "https://mealkit-s3.s3.ap-northeast-2.amazonaws.com/8.jpg",
      price: 18900,
      sale: 0,
      status: 1,
      stock: 20,
      detail: "납작면과 함께하는 맛있는 닭갈비입니다.",
      create_date: "2024-11-06",
   },
   {
      name: "[VIPS] 부채살 찹스테이크",
      brand: "밀샵",
      img: "https://mealkit-s3.s3.ap-northeast-2.amazonaws.com/9.jpg",
      price: 15900,
      sale: 12,
      status: 1,
      stock: 50,
      detail: "부채살로 만든 부드러운 찹스테이크입니다.",
      create_date: "2024-11-06",
   },
   {
      name: "[채선당] 모둠 샤브 전골",
      brand: "밀샵",
      img: "https://mealkit-s3.s3.ap-northeast-2.amazonaws.com/10.jpg",
      price: 12900,
      sale: 14,
      status: 1,
      stock: 45,
      detail: "다양한 재료로 만든 모둠 샤브 전골입니다.",
      create_date: "2024-11-06",
   },
   {
      name: "[북창동순두부] 북창동 순두부찌개",
      brand: "밀샵",
      img: "https://mealkit-s3.s3.ap-northeast-2.amazonaws.com/11.jpg",
      price: 11900,
      sale: 0,
      status: 1,
      stock: 50,
      detail: "북창동 스타일의 순두부찌개입니다.",
      create_date: "2024-11-06",
   },
   {
      name: "[사리원] 소불고기 전골",
      brand: "밀샵",
      img: "https://mealkit-s3.s3.ap-northeast-2.amazonaws.com/12.jpg",
      price: 15900,
      sale: 20,
      status: 1,
      stock: 30,
      detail: "소불고기로 만든 진한 전골입니다.",
      create_date: "2024-11-06",
   },
   {
      name: "[하남돼지집] 푸짐한 돼지고기 콩나물 불고기",
      brand: "밀샵",
      img: "https://mealkit-s3.s3.ap-northeast-2.amazonaws.com/13.jpg",
      price: 12900,
      sale: 0,
      status: 1,
      stock: 50,
      detail: "콩나물과 함께 즐기는 돼지고기 불고기입니다.",
      create_date: "2024-11-06",
   },
   {
      name: "중화풍 양장피",
      brand: "밀샵",
      img: "https://mealkit-s3.s3.ap-northeast-2.amazonaws.com/14.jpg",
      price: 18900,
      sale: 0,
      status: 1,
      stock: 30,
      detail: "중화풍 양장피 요리입니다.",
      create_date: "2024-11-06",
   },
   {
      name: "[캠핑갈땐] 붓처스컷 레드와인 부채살 스테이크",
      brand: "밀샵",
      img: "https://mealkit-s3.s3.ap-northeast-2.amazonaws.com/15.jpg",
      price: 11900,
      sale: 0,
      status: 1,
      stock: 25,
      detail: "레드와인과 함께하는 부채살 스테이크입니다.",
      create_date: "2024-11-06",
   },
   {
      name: "[캠핑갈땐] 요리왕비룡 냄비 돼지고기 김치찜",
      brand: "밀샵",
      img: "https://mealkit-s3.s3.ap-northeast-2.amazonaws.com/16.jpg",
      price: 11900,
      sale: 0,
      status: 1,
      stock: 30,
      detail: "김치와 돼지고기가 조화를 이루는 요리입니다.",
      create_date: "2024-11-06",
   },
   {
      name: "[캠핑갈땐] 킹콩 오리지널 부대찌개",
      brand: "밀샵",
      img: "https://mealkit-s3.s3.ap-northeast-2.amazonaws.com/17.jpg",
      price: 11900,
      sale: 30,
      status: 1,
      stock: 40,
      detail: "오리지널 스타일의 부대찌개입니다.",
      create_date: "2024-11-06",
   },
   {
      name: "[캠핑갈땐] 이차돌 우삼겹 된장찌개",
      brand: "밀샵",
      img: "https://mealkit-s3.s3.ap-northeast-2.amazonaws.com/18.jpg",
      price: 11900,
      sale: 0,
      status: 1,
      stock: 40,
      detail: "우삼겹과 된장이 어우러진 찌개입니다.",
      create_date: "2024-11-06",
   },
   {
      name: "[하남돼지집] 더 푸짐한 돼지불백",
      brand: "밀샵",
      img: "https://mealkit-s3.s3.ap-northeast-2.amazonaws.com/19.jpg",
      price: 14900,
      sale: 12,
      status: 1,
      stock: 25,
      detail: "푸짐한 돼지불백입니다.",
      create_date: "2024-11-06",
   },
   {
      name: "[새벽집] 소고기 된장전골",
      brand: "밀샵",
      img: "https://mealkit-s3.s3.ap-northeast-2.amazonaws.com/27.jpg",
      price: 15900,
      sale: 0,
      status: 1,
      stock: 35,
      detail: "소고기와 된장으로 만든 전골입니다.",
      create_date: "2024-11-06",
   },
   {
      name: "[요리왕비룡] 돼지고기 김치찌개",
      brand: "밀샵",
      img: "https://mealkit-s3.s3.ap-northeast-2.amazonaws.com/20.jpg",
      price: 12900,
      sale: 0,
      status: 1,
      stock: 50,
      detail: "김치와 돼지고기가 들어간 찌개입니다.",
      create_date: "2024-11-06",
   },
   {
      name: "[현대옥] 황태콩나물국밥",
      brand: "밀샵",
      img: "https://mealkit-s3.s3.ap-northeast-2.amazonaws.com/21.jpg",
      price: 8900,
      sale: 19,
      status: 1,
      stock: 45,
      detail: "황태와 콩나물이 들어간 국밥입니다.",
      create_date: "2024-11-06",
   },
   {
      name: "[매드포갈릭] 갈릭 부채살 스테이크",
      brand: "밀샵",
      img: "https://mealkit-s3.s3.ap-northeast-2.amazonaws.com/22.jpg",
      price: 19900,
      sale: 0,
      status: 1,
      stock: 30,
      detail: "갈릭 소스와 함께하는 부채살 스테이크입니다.",
      create_date: "2024-11-06",
   },
   {
      name: "[조선의 밥상] 삼겹살 구이",
      brand: "밀샵",
      img: "https://mealkit-s3.s3.ap-northeast-2.amazonaws.com/23.jpg",
      price: 15900,
      sale: 50,
      status: 1,
      stock: 50,
      detail: "신선한 삼겹살을 구운 요리입니다.",
      create_date: "2024-11-06",
   },
   {
      name: "[장터] 생선구이 정식",
      brand: "밀샵",
      img: "https://mealkit-s3.s3.ap-northeast-2.amazonaws.com/24.jpg",
      price: 13900,
      sale: 10,
      status: 1,
      stock: 45,
      detail: "바삭하게 구운 생선과 반찬이 함께 나옵니다.",
      create_date: "2024-11-06",
   },
   {
      name: "[시골밥상] 된장찌개 정식",
      brand: "밀샵",
      img: "https://mealkit-s3.s3.ap-northeast-2.amazonaws.com/25.jpg",
      price: 11900,
      sale: 20,
      status: 1,
      stock: 50,
      detail: "정성껏 만든 된장찌개와 밥입니다.",
      create_date: "2024-11-06",
   },
   {
      name: "[파스타하우스] 해물파스타",
      brand: "밀샵",
      img: "https://mealkit-s3.s3.ap-northeast-2.amazonaws.com/26.jpg",
      price: 15900,
      sale: 0,
      status: 1,
      stock: 40,
      detail: "신선한 해물이 가득한 파스타입니다.",
      create_date: "2024-11-06",
   },
];
